export { default as Header } from "./header/Header";
export { default as Footer } from "./footer/Footer";
export { default as Blog } from "./blog/Blog";
export { default as Damage } from "./damage/Damage";
export { default as Whatis } from "./whatis/Whatis";
export { default as Labcard } from "./Lab_card/Labcard";
export { default as LabStats } from "./LabStats/LabStats";
export { default as LabExplanation } from "./LabExplanation/LabExplanation";
export { default as LearningSteps } from "./LearningSteps/LearningSteps";